@startuml CruiseControl

skinparam ActivityBackgroundColor #F0EEFF
skinparam ActivityBorderColor #7A60D9
skinparam ArrowColor #7A60D9
skinparam ActivityDiamondBackgroundColor #FFF0F5
skinparam ActivityDiamondBorderColor #D94A8C

start

:User input target speed;
:AutopilotSystem.setCruiseSpeed(speed);
:set targetSpeed = speed;
:set mode = CRUISE_CONTROL;

repeat

  :AutopilotSystem.update();
  :SpeedSensor.getSpeed() → currentSpeed;

  if (SpeedSensor.isOverLimit()?) then (ya)
    :Brake.apply();
    :displayAlert("Kecepatan melebihi batas!");
    stop
  endif

  :SpeedSensor.maintainSpeed(targetSpeed);

  if (maintainSpeed == true?) then (ya)
    :Kecepatan stabil\ntidak ada aksi;
  elseif (currentSpeed < targetSpeed?) then (ya)
    :Engine.accelerate();
  else (currentSpeed > targetSpeed)
    :Brake.apply();
  endif

  if (ObjectDetector.isObstacleAhead()?) then (ya)
    :set mode = COLLISION_AVOIDANCE;
    :handleObstacle();
    stop
  endif

repeat while (mode == CRUISE_CONTROL?) is (ya)
-> tidak;

:Cruise Control selesai;
stop

@enduml