@startuml EmergencyStop

skinparam ActivityBackgroundColor #FFF0F0
skinparam ActivityBorderColor #D94A4A
skinparam ArrowColor #D94A4A
skinparam ActivityDiamondBackgroundColor #FFF0F5
skinparam ActivityDiamondBorderColor #D94A8C

start

if (Pemicu Emergency Stop?) then (Auto urgent)
  :ObjectType PEDESTRIAN atau UNKNOWN;
  :Obstacle threat dalam minSafeDistance;
elseif (Speed over limit)
  :SpeedSensor.isOverLimit() == true;
elseif (Manual GUI/Console)
  :User pilih Emergency Stop Manual;
endif

if (Pemicu dari autopilot?) then (ya)
  :mode = EMERGENCY_STOP;
  :AutopilotSystem.gradualEmergencyStop();
  repeat
    :Brake.emergencyBrake();
    :Engine.brake();
    :SpeedSensor -= 5 KM/Jam;
    :Tunggu 1 detik jika speed masih > 0;
  repeat while (SpeedSensor.currentSpeed > 0?) is (ya)
  ->tidak;

  :Shift down sampai gigi rendah jika perlu;
  :AutopilotSystem.deactivate();
  :Car.driveStraight();
else (manual)
  :Car.disableAutopilot();
  :AutopilotSystem.deactivate();
  repeat
    :Car.applyBrake(5.0f);
    :Tunggu 1 detik;
  repeat while (Car.currentSpeed > 0?) is (ya)
  ->tidak;

  :Car.stop();
endif

:Kecepatan = 0;
:Gigi = 0;
:reverseMode = false;
:Lampu sen = Mati;
:Mesin tetap mengikuti kondisi sebelumnya;

if (BBM habis?) then (ya)
  :Mobil berhenti tetapi mesin tidak dimatikan;
endif

:FuelTank.save("fuel-level.txt");
:Tampilkan pesan emergency stop selesai;

stop

@enduml
